mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=cachet
    - MYSQL_DATABASE=cachet
    - MYSQL_USER=cachet
    - MYSQL_PASSWORD=cachet
cachet:
  build: .
  ports:
    - 80:8000
  links:
    - mysql:mysql
  environment:
    - DB_HOST=mysql
    - DB_DATABASE=cachet
    - DB_USERNAME=cachet
    - DB_PASSWORD=cachet
